apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-service-config
  namespace: nexus
data:
  PORT: "8080"
  RUST_LOG: "api=debug,tower_http=debug"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-client-config
  namespace: nexus
data:
  VITE_API_BASE: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-admin-config
  namespace: nexus
data:
  VITE_API_BASE: ""
