apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - nexus-service.yaml
  - nexus-client.yaml
  - nexus-admin.yaml
  - ingress.yaml
  - hpa.yaml
